Internal review of cmake and github actions update
saleae/SDQAnalyzer pull request #1
Opened 2022-03-23 20:28 UTC by nbanerje

* update to cmake and github actions
* Removed ifdef for protocol search as well

TODO:
@Marcus10110 when you have a chance I am not sure why the simulator does not produce protocol results. Data is definitely being generated, but it appears the analyzer thinks it isn't valid.
<img width="1216" alt="Screen Shot 2022-03-23 at 2 26 55 PM" src="https://user-images.githubusercontent.com/147009/159789647-0d34335f-bb74-4413-afba-1520c7a02e21.png">

2022-03-28 21:15 UTC, Marcus10110 requested changes
2 things:
1. delete the .vscode folder. (don't add it to gitignore though)
2. delete the existing 'readme.saleae.md' file, since that's now outdated.

2022-03-28 21:15 UTC, Marcus10110 commented on .vscode/settings.json
> +{
@nbanerje let's not commit the .vscode folder.

2022-03-28 21:16 UTC, nbanerje commented on .vscode/settings.json
> +{
oof how did that sneek in there! should we add it to .gitignore?

2022-05-26 18:16 UTC, Marcus10110 commented
Closing this, since this has been merged upstream.
@nbanerje I suggest we delete the entire forked repo on github once we're done, to reduce community confusion over what's the best fork to use.

2022-05-26 18:16 UTC, closed without merging